data:
  data_source: yfinance
  default_interval: 15m
  default_period: 5d
strategy:
  long_window: 50
  min_volume: 500000
  short_window: 20
trading:
  initial_capital: 100000.0
  max_portfolio_risk_pct: 0.10
  max_position_size_pct: 0.05
  max_positions: 5
  stop_loss_pct: 0.03
  symbols:
  - AAPL
  - MSFT
  - GOOGL
